In [103]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [104]:
data = pd.read_csv("train.csv")
#data = pd.read_csv('E:\Third Year\Third Year Second term\Supervised\Ass2\digit-recognizer/train.csv')
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [105]:
data = np.array(data)
np.random.shuffle(data)

In [106]:
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets
print(m, n)
#784 feature colmn & 1col is label
#4200 row

42000 785


In [107]:
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
m_train = X_train.shape

In [108]:
print(Y_train.shape)

(41000,)


In [109]:
print(X_train.shape)

(784, 41000)


In [110]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

In [111]:
def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

In [112]:
def ReLU(Z):
    return np.maximum(Z, 0)

In [113]:
def ReLU_deriv(Z):
    return Z > 0

In [114]:
# def sigmoid(x):
#     return 1.0/(1+np.exp(-x))

In [115]:
# def sigmoid_drivitive(x):
#     return x*(1.0 - x)

In [116]:
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

In [117]:
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

In [118]:
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [119]:
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [120]:
def get_predictions(A2):
    return np.argmax(A2, 0)

In [121]:
def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

In [126]:
def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y)*100)
    return W1, b1, W2, b2

In [132]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10 , 2000)

Iteration:  0
[6 6 6 ... 8 8 8] [8 3 3 ... 5 1 9]
10.329268292682926
Iteration:  10
[0 0 0 ... 8 9 8] [8 3 3 ... 5 1 9]
14.321951219512194
Iteration:  20
[0 0 0 ... 9 9 8] [8 3 3 ... 5 1 9]
21.01951219512195
Iteration:  30
[0 0 0 ... 9 9 9] [8 3 3 ... 5 1 9]
27.526829268292687
Iteration:  40
[0 0 0 ... 9 1 9] [8 3 3 ... 5 1 9]
36.77317073170732
Iteration:  50
[0 0 6 ... 9 1 9] [8 3 3 ... 5 1 9]
42.58536585365854
Iteration:  60
[3 0 3 ... 9 1 9] [8 3 3 ... 5 1 9]
47.412195121951214
Iteration:  70
[3 0 3 ... 9 1 9] [8 3 3 ... 5 1 9]
52.44390243902439
Iteration:  80
[3 3 3 ... 5 1 9] [8 3 3 ... 5 1 9]
56.43414634146341
Iteration:  90
[3 3 3 ... 5 1 9] [8 3 3 ... 5 1 9]
59.390243902439025
Iteration:  100
[3 3 3 ... 5 1 9] [8 3 3 ... 5 1 9]
61.89512195121951
Iteration:  110
[3 3 3 ... 5 1 9] [8 3 3 ... 5 1 9]
64.15365853658537
Iteration:  120
[3 3 3 ... 5 1 9] [8 3 3 ... 5 1 9]
66.14634146341464
Iteration:  130
[3 3 3 ... 5 1 9] [8 3 3 ... 5 1 9]
67.82682926829268
Iteration:  140
[3 3 3 ...